name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: dyalog/dyalog
    steps:
         - run: (echo $GITHUB_WORKSPACE)
         - run: (pwd)
         - run: (/opt/mdyalog/18.2/64/unicode/scriptbin/dyalogscript build/build.apl)
         - uses: actions/upload-artifact@v3
           with:
              name: artifacts
              path: ./**/*.html
