name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: dyalog/dyalog
      options: --user root
    steps:
         - uses: actions/checkout@v2
         - run: git submodule update --init --recursive
         - run: (/opt/mdyalog/18.2/64/unicode/scriptbin/dyalogscript "bin/build.apl")
         - uses: actions/upload-artifact@v3
           with:
              name: artifacts
              path: ./**/*.html
