name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: dyalog/dyalog
      options: --user root
    steps:
         - run: apt update
         - run: apt-get install -y git
         - uses: actions/checkout@v2
           with: 
            submodules: recursive
         - run: export SESSION_FILE=/opt/mdyalog/18.2/64/unicode/default.dse
         - run: ./bin/build.apl
         - uses: actions/upload-artifact@v3
           with:
              name: artifacts
              path: ./**/*.html
