name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: dyalog/dyalog
    steps:
         - uses: actions/checkout@v2
         - run: (ls $GITHUB_WORKSPACE)
         - run: (pwd)
         - run: (/opt/mdyalog/18.2/64/unicode/scriptbin/dyalogscript "$GITHUB_WORKSPACE/build/build.apl")
         - uses: actions/upload-artifact@v3
           with:
              name: artifacts
              path: ./**/*.html
